# Generated by Django 5.0.1 on 2024-01-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.URLField(help_text='URL manzili!!')),
                ('soni', models.IntegerField(blank=True, help_text='Obunachilar soni ixtiyoriy!!!', null=True)),
                ('icons', models.CharField(help_text='icon kiriting!! : Masalan: facebook-( fa fa-facebook ),twitter-( fa fa-twitter ), linkedin-( fa fa-linkedin ), rss-( fa fa-rss )', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ManiCatigorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Main Katigoryani kiriting masalan Chetil va boshga, yani Navbar da turovchi ckatigorya', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=25)),
                ('footer', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='font rangi misol: red, #3333, #ffff, #dgdyu5', max_length=250, null=True)),
                ('fonts', models.CharField(blank=True, help_text='fontni: https://fonts.googleapis.com/css?family=Sofia dan oloning!!!', max_length=250, null=True)),
                ('size', models.CharField(blank=True, help_text="font o'lchavi yani px sillarda beriladi!!! masalan: 16px ,32px , 72px ,91px", max_length=250, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reclama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('manzil', models.URLField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Reclama/%y/%m/%d/')),
            ],
        ),
    ]
